// Code generated by "stringer -type=EntityType"; DO NOT EDIT.

package model

import (
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NODE-0]
	_ = x[WAY-1]
	_ = x[RELATION-2]
}

const _EntityType_name = "NODEWAYRELATION"

var _EntityType_index = [...]uint8{0, 4, 7, 15}

func (i EntityType) String() string {
	if i < 0 || i >= EntityType(len(_EntityType_index)-1) {
		return "EntityType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntityType_name[_EntityType_index[i]:_EntityType_index[i+1]]
}
