// Code generated by "stringer --type BlobCompression"; DO NOT EDIT.

package encoder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RAW-0]
	_ = x[ZLIB-1]
	_ = x[LZMA-2]
	_ = x[LZ4-3]
	_ = x[ZSTD-4]
}

const _BlobCompression_name = "RAWZLIBLZMALZ4ZSTD"

var _BlobCompression_index = [...]uint8{0, 3, 7, 11, 14, 18}

func (i BlobCompression) String() string {
	if i < 0 || i >= BlobCompression(len(_BlobCompression_index)-1) {
		return "BlobCompression(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BlobCompression_name[_BlobCompression_index[i]:_BlobCompression_index[i+1]]
}
